# .scrutinizer.yml
checks:
    php: true

filter:
    paths: [ "src/*" ]
    excluded_paths:
        - "tests/*"
        - "*/vendor/*"

build:
    environment:
        timezone: UTC
        php:
            version: 5.6
        mysql: 5.5
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true